import type {
  DataType,
  BSCPerspective,
  PRISMDimension,
  ChartType,
  AggregationType,
  FlowStep,
  Theme
} from './common';

// ─── File Loading Models ─────────────────────────────────────────────────────

/**
 * @description Result of a successful file load operation.
 * Contains metadata and parsed data from the uploaded file.
 */
export interface FileLoadResult {
  /** Original file name */
  readonly fileName: string;
  /** File size in bytes */
  readonly fileSize: number;
  /** Number of sheets (1 for CSV) */
  readonly sheetCount: number;
  /** Total rows processed (max 100,000) */
  readonly totalRows: number;
  /** Whether the file was truncated to 100K rows */
  readonly wasTruncated: boolean;
  /** Parsed data per sheet */
  readonly sheets: SheetData[];
}

/**
 * @description Parsed data for a single sheet within a file.
 */
export interface SheetData {
  /** Sheet name */
  readonly name: string;
  /** Column header names */
  readonly headers: string[];
  /** Data rows (max 100,000 total across all sheets) */
  readonly rows: unknown[][];
  /** Original row count before truncation */
  readonly originalRowCount: number;
}

// ─── Detection Models ────────────────────────────────────────────────────────

/**
 * @description Metadata about a single column detected in a sheet.
 */
export interface ColumnInfo {
  /** Column name from header */
  readonly name: string;
  /** Type detected automatically via sampling */
  readonly detectedType: DataType;
  /** Type assigned (may be modified by user) */
  assignedType: DataType;
  /** Percentage of empty values (0-100) */
  readonly emptyPercentage: number;
  /** Count of non-empty records */
  readonly recordCount: number;
  /** True if emptyPercentage > 30 */
  readonly hasWarning: boolean;
}

/**
 * @description Structure analysis result for a single sheet.
 */
export interface SheetStructure {
  /** Name of the sheet */
  readonly sheetName: string;
  /** Column information array */
  readonly columns: ColumnInfo[];
  /** Total records in this sheet */
  readonly totalRecords: number;
}

/**
 * @description Complete result of the structure detection analysis.
 */
export interface DetectionResult {
  /** Structure per analyzed sheet */
  readonly sheets: SheetStructure[];
  /** Number of sheets analyzed (max 50) */
  readonly analyzedSheets: number;
  /** Number of sheets skipped */
  readonly skippedSheets: number;
  /** Whether at least one sheet has valid tabular structure */
  readonly hasValidStructure: boolean;
}

// ─── PRISM Models ────────────────────────────────────────────────────────────

/**
 * @description Detail about a specific problem found during PRISM evaluation.
 */
export interface ProblemDetail {
  /** Location identifier (column name or row index) */
  readonly location: string;
  /** Human-readable description of the problem */
  readonly description: string;
  /** Impact on the dimension score (0-100) */
  readonly impact: number;
}

/**
 * @description Score and observations for a single PRISM dimension.
 */
export interface DimensionScore {
  /** The dimension being evaluated */
  readonly dimension: PRISMDimension;
  /** Quality score (integer 0-100) */
  readonly score: number;
  /** Textual observations about this dimension */
  readonly observations: string[];
  /** Specific problems found (max 10 per dimension) */
  readonly problems: ProblemDetail[];
}

/**
 * @description Complete result of PRISM quality evaluation.
 */
export interface PRISMResult {
  /** Scores for all 5 dimensions */
  readonly dimensions: DimensionScore[];
  /** True if all dimensions score 0 (blocks visualization) */
  readonly isBlockingQuality: boolean;
  /** True if Integrity dimension < 30 */
  readonly hasLowIntegrity: boolean;
  /** True if any dimension < 60 */
  readonly hasWarningDimensions: boolean;
}

// ─── Visualization Models ────────────────────────────────────────────────────

/**
 * @description A chart suggestion generated by the visualization catalog.
 */
export interface ChartSuggestion {
  /** Unique identifier */
  readonly id: string;
  /** Type of chart suggested */
  readonly type: ChartType;
  /** Suggested title */
  readonly title: string;
  /** Column names involved in this chart */
  readonly columns: string[];
  /** Rationale for suggesting this chart type */
  readonly rationale: string;
}

/**
 * @description A KPI suggestion generated from data analysis.
 */
export interface KPISuggestion {
  /** Unique identifier */
  readonly id: string;
  /** KPI display name */
  readonly name: string;
  /** Aggregation operation used */
  readonly aggregation: AggregationType;
  /** Primary column for the KPI */
  readonly column: string;
  /** Descriptive formula */
  readonly formula: string;
  /** Computed value from current data, null if not computable */
  readonly computedValue: number | null;
}

/**
 * @description Configuration for rendering a visualization.
 */
export interface VisualizationConfig {
  /** Color scheme or specific colors */
  readonly colors: string[];
  /** Axis and data labels */
  readonly labels: Record<string, string>;
  /** Data range constraints */
  readonly dataRange: {
    readonly min?: number;
    readonly max?: number;
    readonly startDate?: string;
    readonly endDate?: string;
  };
}

/**
 * @description A configured visualization (suggested or custom).
 */
export interface Visualization {
  /** Unique identifier */
  readonly id: string;
  /** Type of chart */
  readonly type: ChartType;
  /** Display title (max 100 chars) */
  readonly title: string;
  /** Rendering configuration */
  readonly config: VisualizationConfig;
  /** Column names assigned to this visualization */
  readonly dataColumns: string[];
  /** Whether this was manually created by the user */
  readonly isCustom: boolean;
}

// ─── Objectives Models ───────────────────────────────────────────────────────

/**
 * @description A strategic objective defined by the user.
 */
export interface StrategicObjective {
  /** Unique identifier */
  readonly id: string;
  /** Objective name (max 150 chars) */
  readonly name: string;
  /** Objective description (max 500 chars) */
  readonly description: string;
  /** BSC perspective this objective belongs to */
  readonly perspective: BSCPerspective;
  /** IDs of KPIs linked to this objective */
  readonly linkedKPIIds: string[];
}

/**
 * @description Represents a link between a KPI and a strategic objective.
 */
export interface KPILink {
  /** ID of the linked KPI */
  readonly kpiId: string;
  /** ID of the linked objective */
  readonly objectiveId: string;
}

// ─── IA Models ───────────────────────────────────────────────────────────────

/**
 * @description Configuration for an IA provider.
 */
export interface IAProviderConfig {
  /** Unique provider identifier */
  readonly providerId: string;
  /** API key (stored encrypted) */
  readonly apiKey: string;
  /** Specific model name */
  readonly model: string;
  /** Base URL for the provider (e.g., localhost:11434 for Ollama) */
  readonly baseUrl: string;
}

/**
 * @description Statistical summary for a single column.
 */
export interface StatsSummary {
  /** Minimum value (for numeric columns) */
  readonly min?: number;
  /** Maximum value (for numeric columns) */
  readonly max?: number;
  /** Mean value (for numeric columns) */
  readonly mean?: number;
  /** Median value (for numeric columns) */
  readonly median?: number;
  /** Count of non-null values */
  readonly count: number;
  /** Count of null/empty values */
  readonly nullCount: number;
  /** Distinct value count */
  readonly distinctCount: number;
}

/**
 * @description Metadata about a dataset sent to IA providers.
 * Never contains individual record values.
 */
export interface DatasetMetadata {
  /** Column names */
  readonly columnNames: string[];
  /** Data types per column */
  readonly columnTypes: DataType[];
  /** Total row count */
  readonly rowCount: number;
  /** Statistical summaries per column (keyed by column name) */
  readonly statistics: Record<string, StatsSummary>;
}

/**
 * @description Response received from an IA provider.
 */
export interface IAResponse {
  /** Formatted response content */
  readonly content: string;
  /** Provider that generated this response */
  readonly providerId: string;
  /** Timestamp of the response */
  readonly timestamp: number;
}

// ─── Document Models ─────────────────────────────────────────────────────────

/**
 * @description Threshold conditions for KPI evaluation levels.
 */
export interface ThresholdConditions {
  /** Optimal threshold value */
  readonly optimal: number;
  /** Acceptable threshold value */
  readonly acceptable: number;
  /** Rejected threshold value */
  readonly rejected: number;
}

/**
 * @description Technical sheet for a single KPI in the generated document.
 */
export interface KPITechnicalSheet {
  /** Abbreviated code */
  readonly code: string;
  /** Full KPI name */
  readonly fullName: string;
  /** Associated objective name */
  readonly objectiveName: string;
  /** Calculation formula */
  readonly formula: string;
  /** Evaluation conditions with three levels */
  readonly conditions: ThresholdConditions;
}

/**
 * @description Metadata included in the generated BSC document.
 */
export interface DocumentMetadata {
  /** Generation date in ISO 8601 format (YYYY-MM-DD) */
  readonly generationDate: string;
  /** Source file name */
  readonly sourceFileName: string;
  /** PRISM scores per dimension */
  readonly prismScores: Record<PRISMDimension, number>;
  /** IA provider used for assistance */
  readonly iaProvider: string;
}

/**
 * @description Structure of the generated BSC document sections.
 */
export interface BSCDocument {
  /** Document metadata */
  readonly metadata: DocumentMetadata;
  /** Introduction section content */
  readonly introduction: string;
  /** Strategic objectives section */
  readonly objectives: BSCObjectivesSection[];
  /** BSC dimensions section */
  readonly dimensions: BSCDimensionSection[];
  /** KPI identification section */
  readonly kpiIdentification: KPITechnicalSheet[];
  /** Data section with datasets and charts */
  readonly dataSection: DataSectionContent;
  /** Quantitative/qualitative analysis */
  readonly analysis: AnalysisEntry[];
}

/**
 * @description A BSC dimension section in the document.
 */
export interface BSCDimensionSection {
  /** BSC perspective */
  readonly perspective: BSCPerspective;
  /** KPIs under this perspective */
  readonly kpis: KPITechnicalSheet[];
  /** Whether this perspective was included (has valid KPIs) */
  readonly included: boolean;
  /** Reason for exclusion if not included */
  readonly exclusionReason?: string;
}

/**
 * @description Objectives section in the generated document.
 */
export interface BSCObjectivesSection {
  /** Objective name */
  readonly name: string;
  /** Objective description */
  readonly description: string;
  /** BSC perspective */
  readonly perspective: BSCPerspective;
  /** Actions derived from analysis */
  readonly actions: string[];
}

/**
 * @description Content for the data section of the document.
 */
export interface DataSectionContent {
  /** Datasets used with their dimensions */
  readonly datasets: DatasetInfo[];
  /** Transformations applied */
  readonly transformations: TransformationEntry[];
  /** Charts with interpretations */
  readonly charts: ChartEntry[];
}

/**
 * @description Information about a dataset used in the analysis.
 */
export interface DatasetInfo {
  /** Dataset/file name */
  readonly name: string;
  /** Number of rows */
  readonly rows: number;
  /** Number of columns */
  readonly columns: number;
}

/**
 * @description A transformation applied to the data.
 */
export interface TransformationEntry {
  /** Description of the transformation */
  readonly description: string;
  /** Input state description */
  readonly input: string;
  /** Output state description */
  readonly output: string;
}

/**
 * @description A chart included in the document with interpretation.
 */
export interface ChartEntry {
  /** Chart title */
  readonly title: string;
  /** Chart type */
  readonly type: ChartType;
  /** Interpretation paragraph */
  readonly interpretation: string;
}

/**
 * @description An entry in the analysis table linking KPIs to analysis type.
 */
export interface AnalysisEntry {
  /** KPI name */
  readonly kpiName: string;
  /** Type of analysis (quantitative or qualitative) */
  readonly analysisType: 'quantitative' | 'qualitative';
  /** Tool or method used for measurement */
  readonly tool: string;
}

// ─── User Customizations ─────────────────────────────────────────────────────

/**
 * @description User customizations preserved across document regeneration.
 */
export interface UserCustomizations {
  /** Custom section titles (keyed by section identifier) */
  readonly sectionTitles: Record<string, string>;
  /** Custom interpretation texts (keyed by chart/KPI identifier) */
  readonly interpretationTexts: Record<string, string>;
  /** Custom objective ordering (array of objective IDs) */
  readonly objectiveOrder: string[];
}

// ─── Encrypted Payload ───────────────────────────────────────────────────────

/**
 * @description Encrypted data payload produced by AES-256-GCM encryption.
 */
export interface EncryptedPayload {
  /** Base64-encoded ciphertext */
  readonly ciphertext: string;
  /** Base64-encoded initialization vector */
  readonly iv: string;
  /** Base64-encoded authentication tag */
  readonly tag: string;
}

// ─── Log Models ──────────────────────────────────────────────────────────────

/**
 * @description A single log entry recorded by the LogService.
 */
export interface LogEntry {
  /** ISO 8601 timestamp */
  readonly timestamp: string;
  /** Module that generated the log */
  readonly module: string;
  /** Log level */
  readonly level: 'error' | 'warning' | 'info' | 'security';
  /** Log message */
  readonly message: string;
  /** Stack trace if applicable */
  readonly stackTrace?: string;
  /** Additional context */
  readonly context?: Record<string, unknown>;
}

/**
 * @description Filter options for querying logs.
 */
export interface LogFilter {
  /** Filter by module name */
  readonly module?: string;
  /** Filter by log level */
  readonly level?: LogEntry['level'];
  /** Filter logs after this timestamp */
  readonly since?: string;
  /** Maximum number of entries to return */
  readonly limit?: number;
}

// ─── Session State ───────────────────────────────────────────────────────────

/**
 * @description Complete session state persisted in localStorage.
 * Serialized as JSON with encrypted API keys.
 */
export interface SessionState {
  /** Schema version for future migrations */
  readonly version: number;
  /** Unique session identifier */
  readonly sessionId: string;
  /** Timestamp of last modification (Unix ms) */
  readonly lastModified: number;
  /** Current step in the onboarding flow */
  readonly currentStep: FlowStep;
  /** Loaded file data, null if no file loaded */
  readonly fileData: FileLoadResult | null;
  /** Structure detection result */
  readonly detectionResult: DetectionResult | null;
  /** PRISM audit result */
  readonly prismResult: PRISMResult | null;
  /** Selected and custom visualizations */
  readonly visualizations: Visualization[];
  /** Selected KPIs */
  readonly selectedKPIs: KPISuggestion[];
  /** Strategic objectives defined by user */
  readonly objectives: StrategicObjective[];
  /** KPI-Objective links */
  readonly links: KPILink[];
  /** IA configuration and history */
  readonly iaConfig: {
    readonly activeProviderId: string | null;
    readonly providers: IAProviderConfig[];
    readonly queryHistory: IAResponse[];
  };
  /** User customizations for document regeneration */
  readonly userCustomizations: UserCustomizations;
  /** UI preferences */
  readonly uiPreferences: {
    readonly theme: Theme;
    readonly locale: string;
  };
}
